/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as otcSol from "./OTC.sol";
export type { otcSol };
export type { AllowanceCrowdsale } from "./AllowanceCrowdsale";
export type { Box } from "./Box";
export type { BoxV2 } from "./BoxV2";
export type { Crowdsale } from "./Crowdsale";
export type { Greeter } from "./Greeter";
export type { ITManToken } from "./ITManToken";
export type { ITManTokenCrowdsale } from "./ITManTokenCrowdsale";
export type { TimedCrowdsale } from "./TimedCrowdsale";
